export const config = {
    API_URL: 'https://essence.fyi', // 'http://localhost:5000', // 'https://essence.fyi'
    NEW_DIVIDER_KEYWORD: 'New divider...',
    DEFAULT_SAVED_LIST: // default saved list, shown when no saved list is found
        [
            {key: 0, subject: 'Vacation', content: 
            [
                {id: '7eb924b1-a52c-4a10-b9cd-a4590e1c171a', title: 'Cleveland Trip', url: 'https://www.thegeographicalcure.com/post/2-days-in-cleveland-itinerary', 
                long_summary: [{'title': 'Exploring Cleveland Ohio: A 48-Hour Itinerary', 'url': 'https://www.thegeographicalcure.com/post/2-days-in-cleveland-itinerary', 'text': [{key: 'Activity name', value: 'Perfect 2 Days In Cleveland Ohio Itinerary'}, {key: 'Accommodation', value: ''}, {key: 'Transportation', value: 'bus, taxi'}, {key: 'Itinerary table', value: [['Day', 'Destination', 'Details'], ['1', 'Downtown Cleveland', 'Rock and Roll Hall of Fame, Cleveland Arcade, 4th Street, Heinen’s Supermarket, Public Square, Free Stamp sculpture'], ['2', 'Ohio City Neighborhood', 'West Side Market, Cleveland House of Blues, Lincoln Park, A Christmas Storyhouse, dinner in Tremont'], ['3', 'Uptown/Little Italy', 'Presti’s Bakery, Lake View Cemetery, MOCA, Cleveland Museum of Art']]}]}], qa_list: [['Places to eat?', 'In Cleveland, you can find plenty of places to eat, such as farm to table eateries, vegan fare, and breweries on 25th Street. West Side Market is a great place to shop for your lunch, with over 100 vendors. In Tremont, you can have dinner at Fahrenheit or Dante on Professor Street, or get breakfast at Grumpy’s Cafe or Lucky’s Cafe. In Little Italy, you can grab breakfast at Presti’s Bakery and there is also a cute cafe called Algebra. You can also try seafood cuisine at a waterfront restaurant such as Alley Cat Oyster Bar.', 1673554307038]] }, 
                {id: 'eb301a10-59bc-47aa-bf68-e5879f3857b1', title: 'Greece Trip', url: 'https://www.toptravelsights.com/greece-in-7-days-itinerary/', 
                long_summary: [{'title': '7-Day Greece Itinerary', 'url': 'https://www.toptravelsights.com/greece-in-7-days-itinerary/', 'text': [{key: 'Activity name', value: 'Greece in 7 Days'}, {key: 'Accommodation', value: 'Evripidou Suites, Electra Metropolis, Old Town Hall, Suites and Apartments, Argonauta Hotel, Paros Palace, Aegean Village, Aethrio Sunset Village, Laokasti Villas, Aspaki by Art Maisons, Galatia Villas'}, {key: 'Transportation', value: 'rental car, ferry'}, {key: 'Best Seasons', value: 'summer (mid-June to mid-September)'}, {key: 'Preparation', value: 'book ferry ticket in advance, plan in advance if staying in a lesser-known island'}, {key: 'Budget', value: 'varies'}, {key: 'Itinerary table', value: [['Day', 'Destination', 'Details'], ['1', 'Athens', 'Acropolis, Acropolis Museum, Ancient Agora, Plaka'], ['2', 'Peloponnese', 'Mycenae, Epidaurus, Nafplio, Corinth Canal'], ['3', 'Athens/Meteora', "Roman Forum, Hadrian's Library, Philopappou Hill, Lycabettus Hill, Monasteries of Meteora"], ['4', 'Paros', 'Old Town, Church of Panagia Ekatontapiliani, Museum of Byzantine Culture, Antine Art, Archaeological Museum'], ['5', 'Paros', 'Naoussa, Kolymbithres Beach'], ['6', 'Santorini', 'Oia (The 3 blue domes of Oia, Sunset view, Ammoudi Bay), Fira (Old Town, Museum of Prehistoric Thera)'], ['7', 'Santorini', 'Akrotiri, Fira (Old Town, Museum of Prehistoric Thera), Caldera boat tour, Catamaran Cruise']]}, {key: 'If You Have More/Less Time', value: ''}, {key: 'Greece itinerary – 10 days', value: 'Kalambaka to see the Monasteries of Meteora, Delphi, Nafplio, Sparta, Mystras; road trip across the Peloponnese'}, {key: 'Greece itinerary – 5 days', value: 'Athens, Paros, Naoussa, Kolymbithres Beach (skip Santorini)'}]}], qa_list: []}, 
                {id: '60e7473e-193d-4388-a1b9-dbb8b68f2de7', title: 'Barcelona Trip', url: 'https://www.findingtheuniverse.com/3-day-barcelona-itinerary/', 
                long_summary: [{'title': 'Exploring Barcelona: 3-day Itinerary', 'url': 'https://www.findingtheuniverse.com/3-day-barcelona-itinerary/', 'text': [{key: 'Activity name', value: '3 Days in Barcelona'}, {key: 'Accommodation', value: 'Leonardo Hotel Las Rambals (£376), Room Mate Carla (£398), H10 Universitat (476), Royal Ramblas (£446), dual hotel rooms (book online). For example, this search on booking.com is set up to just show apartments that will take up to 11 adults'}, {key: 'Transportation', value: 'public transport (individual tickets, T10 card, Hola BCN card, Aerobus, taxi, train), Barcelona City Pass, Go Barcelona Pass, Barcelona Card, Hop on Hop off bus tour (included in Barcelona Pass, individual tickets available), flights to Marrakesh'}, {key: 'Best Seasons', value: 'all year'}, {key: 'Preparation', value: 'booking tickets in advance, buying tickets online, familiarize yourself with public transport, transport cards, adapters for electronics, reserve airport transport, research walking tours, book accommodation online, take advantage of Hop on Hop off bus, use metro system, look for multi-room apartment, reserve tickets online for attractions, use Barcelona City Pass to book timed entry for certain attractions, check for discounts with Barcelona Card, consider Go Barcelona Pass or Gaudi bundle for certain attractions, audioguide included with some attractions, free admission on Sundays for certain attractions, check for night shows.'}, {key: 'Budget', value: 'varies'}, 
                    {key: 'Itinerary table', value: [['Day', 'Activity', 'Details'], ['1', 'Casa Batlló', 'Skip the ticket line, book ticket online, discounts with Barcelona Card'], ['', 'Casa Milá', 'Discounted admission with Barcelona Card'], ['', 'Las Ramblas', 'People watching, outdoor dining'], ['', 'La Boqueria', '19th century design'], ['', 'Mirador de Colom', 'Entry fee, discounts with Barcelona Card'], ['', 'Las Golondrinas Boat Tour', 'Port area, varying tour lengths, book tickets online'], ['', 'Barcelona Aquarium or Catalonia History Museum', 'Tickets online'], ['2', 'Sagrada Familia', 'Buy tickets online, timed entry up to 24 hours in advance, audioguide included, discounts with Barcelona Card for tickets purchased in person, Go Barcelona Pass includes guided tour, Barcelona City Pass includes pre-booked timed entry online, Gaudi bundle includes pre-booked timed entry to the Sagrada Familia and Parc Guell, audioguide that covers both attractions'], ['', 'Park Güell', 'Tickets online, skip the line, discounts with Barcelona City Pass, Go Barcelona Pass includes free guided tour, Barcelona City Pass includes pre-booked timed entry online, Gaudi bundle includes pre-booked timed entry to the Sagrada Familia and Parc Guell, audioguide that covers both attractions'], ['', 'La Barceloneta', 'Stroll along the beach, explore the port'], ['', 'Arc de Triomf', 'Free'], ['', 'Parc de la Ciutadella', 'Free'], ['', 'Picasso Museum', 'Tickets online, discounts with Barcelona City Pass, guided tour available'], ['3', 'Montjuïc', 'Free'], ['', 'Montjuïc Cable Car', 'Ticket online, discounts with Barcelona City Pass'], ['', 'Montjuïc Castle', 'Discounted admission with Barcelona Card, free on Sunday afternoons'], ['', 'Magic Fountain of Montjuïc', 'Night show, free (parts of the fountain may run in the daytime without sound or light), view from steps in front of National Museum of Catalan Art'], ['', 'Chocolate Museum', 'Tickets online, free for Barcelona Card holders'], ['', 'Gothic Quarter', 'Picasso Museum (tickets online, guided tour available), Palau de la Musica Catalana (tickets online, discounts with Barcelona Card for tickets purchased in person, performances available), Barcelona Cathedral (free), Gaudí Exhibition Centre (free), Poble Espanyol (free with Go Barcelona Pass,']]}] }], qa_list: []}, 
                {id: '51f9d57c-e87e-412d-8c1a-a87aa50be21d', title: 'Panama Vacation', url: 'https://www.laidbacktrip.com/posts/panama-travel-itinerary-2-weeks', 
                long_summary: [{'title': 'Exploring Panama: A Perfect Two-Week Itinerary', 'url': 'https://www.laidbacktrip.com/posts/panama-travel-itinerary-2-weeks', 'text': [{key: 'Activity name', value: 'Perfect 2-Weeks Panama Travel Itinerary'}, {key: 'Accommodation', value: 'simple hotel, American-owned hotels'}, {key: 'Eating', value: 'local food, hearty meals'}, {key: 'Transportation', value: 'Uber, taxi, bus, car rental'}, {key: 'Best Seasons', value: 'Spring/Summer'}, {key: 'Preparation', value: 'research, travel insurance, check local warnings'}, {key: 'Budget', value: 'varies'}, {key: 'Itinerary table', value: [['Day', 'Destination', 'Details'], ['1 - 3', 'Panama City', 'Casco Viejo, Panama Viejo, Panama Canal, Soberania National Park'], ['4 - 6', 'El Valle de Anton', 'countryside charm'], ['7 - 10', 'Boquete', 'Baru Volcano, hiking, water rafting, coffee plantation'], ['11 - 14', 'Bocas del Toro', 'island-hopping, biking, beach']]}] }], qa_list: []}
            ]}, 
            {key: 1, subject: 'Scientific', content: 
            [
                {id: '77e018e6-03a1-403a-b293-ebcbdbf6dbfa', title: 'Autocratic Legalism: Dismantling Constitutional Systems by Law', url: 'https://lawreview.uchicago.edu/sites/lawreview.uchicago.edu/files/11%20Scheppele_SYMP_Online.pdf', 
                long_summary: [{'title': 'Autocratic Legalism: Dismantling Constitutional Systems by Law', 'url': 'https://lawreview.uchicago.edu/sites/lawreview.uchicago.edu/files/11%20Scheppele_SYMP_Online.pdf', 'text': [{key: 'Scientific field', value: 'Constitutional democracy'}, {key: 'Background', value: 'Constitutional democracy, flawed but in reasonably good standing, is hit by a transformative election. A charismatic new leader comes to power, propelled by the growing impatience that the electorate feels with things as they are. The leader promises to sweep away the dysfunctions of partisanship, gridlock, bureaucracy.'}, {key: 'Novelty', value: 'Charismatic new leaders are elected by democratic publics and then use their electoral mandates to dismantle by law the constitutional systems they inherited. They deploy the law to achieve their aims and impending autocracy may not be evident at the start.'}, {key: 'Main conclusion', value: 'There is a wide but normatively justifiable variation in the institutional forms and substantive rules that one can find among constitutional-democratic states. Within those legitimate variations, some combinations of these forms and rules prove toxic to the continued maintenance of the liberal forms of constitutional democracy.'}, {key: 'Methods', value: 'Analyzing data from OECD countries and European Union, deploying legal reforms to remove the checks on executive power, limit the challenges to their rule, and undermine the crucial accountability institutions of a democratic state.'}] }], qa_list: [
                    ['Who is the dictator of Hungary?', 'The dictator of Hungary is Prime Minister Viktor Orbán.', 1673611157093], ['How did Viktor Orban come into power?', "Viktor Orban came into power by winning a majority of seats in the Hungarian Parliament in 2010 with 53 percent of the popular vote. He then changed the constitution and passed laws to weaken institutions that could check his power, such as the judiciary, media, prosecutor's office, tax authority, and election commission. He also passed laws that gave him a direct line of control into local governments and appointed his own handpicked candidates to those positions.", 1673611184420], ['How did Orban weaken the media?', "Orban weakened the media by removing opposition figures and neutral experts from public institutions, expanding the length of their successors' terms of office, changing parliamentary procedure so that opposition MPs could not even speak on the floor, and filling other independent institutions with party loyalists.", 1673611229199], ['How do dictators restrict the media?', 'Dictators restrict the media by weakening opposition support structures, monopolizing broadcast media, harassing critics, and tinkering with election rules. They may also rewrite constitutions to make what was once unconstitutional into something legal.', 1673611281959], ['How does Putin dismantle his accountibility?', 'Putin dismantles his accountability by canceling elections of local governors and appointing his own handpicked candidates instead, centralizing many local government functions, handpicking all of the local government leaders to make them personally loyal to him, packing the Constitutional Court of Russia with judges of his own choosing, expanding the number of judges on the Constitutional Court of Russia to give his party control over the court, and using various measures to make it impossible for owners to keep their businesses without accepting a major loss. He also engages in mass human-rights violations, reduces those around him to puppets, and eliminates opposition. The elections that keep Putin in power are rigged in technical ways behind the scenes.', 1673611349424], 
                    ['Do protests work to reduce the power of autocracies?', 'It is difficult to give a simple answer to this question, as it depends on the particular circumstances of each situation. It is possible that protests can be effective in reducing the power of autocracies, but it is also possible that they will not be effective. It is important for people to be aware of the tactics that autocratic legalists use to consolidate power, such as manipulating laws and constitutional systems, and to understand the danger signals that accompany their legal reforms. Civic education can help people to better recognize the signs of danger and to understand how to resist autocracy.', 1673611716608], ['What are examples of protests that helped mitigate the power of autocrats?', "Examples of protests that helped mitigate the power of autocrats include the various measures taken by civil society organizations to challenge the Fidesz government in Hungary, such as protests, legal challenges, and civic education campaigns. Additionally, many countries have seen protests against the legalistic autocrats' efforts to dismantle constitutional constraints, such as their attempts to weaken checks and balances or entrench their own power.", 1673611776616]]}, 
                {id: '6b1acf32-0bd0-4a9a-ba02-37c13368752b', title: '[2301.07265] Pushing the Limits of Detectability: Mixed Dark Matter from Strong Gravitational Lenses', url: 'https://arxiv.org/pdf/2301.07265.pdf', 
                long_summary: [{'title': 'Pushing the Limits of Detectability: Mixed Dark Matter from Strong Gravitational Lenses', 'url': 'https://arxiv.org/pdf/2301.07265.pdf', 'text': [{key: 'Scientific field', value: 'Dark Matter, Strong Gravitational Lensing'}, {key: 'Background', value: 'The CDM paradigm, which posits DM is collisionless as well as cold, predicts the existence of collapsed DM halos down to very small halo masses or length scales.'}, {key: 'Novelty', value: 'We investigate a case where half of the DM is composed of CDM particles and half is WDM particles.'}, {key: 'Main conclusion', value: 'With a set of lenses with different configurations of the main deflector and hence different sensitivities to different mass ranges of the halo mass function, the different forms of suppression of the halo mass function between the warm dark matter model and the mixed dark matter model can be distinguished with 40 lenses.'}, {key: 'Methods', value: 'Strong gravitational lensing, anomalous flux ratio method, statistical modeling.'}] }], qa_list: []}, 
                {id: '418776a2-b5ed-4d48-82b9-42a19a38c8ad', title: '[1706.03762] Attention Is All You Need', url: 'https://arxiv.org/pdf/1706.03762.pdf', 
                long_summary: [{'title': 'Attention-Based Model for Natural Language Processing', 'url': 'https://arxiv.org/pdf/1706.03762.pdf', 'text': [{key: 'Scientific field', value: 'Machine translation, neural networks'}, {key: 'Background', value: 'The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The best performing models also connect the encoder and decoder through an attention mechanism.'}, {key: 'Novelty', value: 'We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely.'}, {key: 'Main conclusion', value: 'Our model achieves 28.4 BLEU on the WMT 2014 English- to-German translation task and 41.8 on the WMT 2014 English-to-French translation task, establishing a new single-model state-of-the-art BLEU score.'}, {key: 'Methods', value: 'Attention mechanisms, self-attention, multi-head attention, scaled dot-product attention, parameter-free position representation.'}] }], qa_list: []}
            ]}, 
            {key: 2, subject: 'Business Analytics', content: 
            [
                {id: '5ef82528-e2da-4132-b92d-ed2cf48390ec', title: 'Amazon ends charity donation program AmazonSmile | TechCrunch', url: 'https://techcrunch.com/2023/01/19/amazon-ends-charity-donation-program-amazonsmile/', 
                long_summary: [{'title': 'AmazonSmile: END Donate 0.5% of Eligible Purchases to Charities', 'url': 'https://techcrunch.com/2023/01/19/amazon-ends-charity-donation-program-amazonsmile/', 'text': [{key: 'Main company', value: 'Amazon'}, {key: 'Business/service', value: 'AmazonSmile, donation program'}, {key: 'Valuation', value: '$974B'}, {key: 'Product', value: 'AmazonSmile, separate website for browsing/buying items'}, {key: 'Features', value: '0.5% of cost of eligible products towards charities'}, {key: 'Business decisions', value: [['Type', 'Details'], ['Closing date', 'February 20, 2023'], ['Donations', '$400M since 2013'], ['Layoffs', 'Directly tied to end of AmazonSmile program']]}] }], qa_list: []}, 
                {id: 'aa6373f4-7f40-4024-b622-69be69e10ac4', title: 'S&P 500 Plummets on Weak Consumer Spending and Inflation Data', url: 'https://finance.yahoo.com/news/stock-market-news-live-updates-january-19-2023-130007540.html', 
                long_summary: [{'title': 'S&P 500 Plummets on Weak Consumer Spending and Inflation Data', 'url': 'https://finance.yahoo.com/news/stock-market-news-live-updates-january-19-2023-130007540.html', 'text': [{key: 1, value: 'Stocks plummeted Wednesday after new government data showed a slowdown in consumer spending activity and a reading on wholesale price inflation showed signs that price pressures are easing in the economy'}, {key: 2, value: 'Federal Reserve Vice Chair Lael Brainard said Thursday that the central bank should stay the course in making monetary policy more restrictive'}, {key: 3, value: "Bank of New York President John Williams and Bank of Boston President Susan Collins are expected to speak at two separate events before the Fed's next monetary policy meeting"}, {key: 4, value: 'New US home construction decreased 1.4% in December, the fourth consecutive monthly decline'}, {key: 5, value: 'Initial unemployment claims dropped to 190,000 compared to 205,000 in the previous week'}, {key: 6, value: 'The Philadelphia Fed Manufacturing Index improved modestly in January to -8.9 from -13.8 in December'}, {key: 7, value: 'Analysts are downgrading their forecasts for earnings growth, with the consensus for earnings drop being 3.9%'}, {key: 8, value: 'Netflix (NFLX) is set to report earnings on Thursday after the market closes'}, {key: 9, value: 'Shares of Alcoa (AA) dropped Thursday after the U.S. based aluminum producer reported lower prices for aluminum products'}, {key: 10, value: 'Procter & Gamble (PG) shares slipped nearly 1% Thursday morning after the company raised its full-year sales forecast'}, {key: 11, value: 'Amazon (AMZN) shares were down 2% as the company reported it would shut down its charity donation program AmazonSmile'}, {key: 12, value: 'West Texas Intermediate (WTI) rose nearly 1% to $80 per barrel, and gas prices are up 5.33% since the end of 2022'}] }], qa_list: []}, 
                {id: 'f9cf3430-27f5-4a27-a010-18397fa9d63d', title: 'FTT Exchange Token Recovers 35% Following Interview', url: 'https://finance.yahoo.com/news/ftx-token-jumps-after-ceo-says-viable-business-could-emerge-from-bankruptcy-172411742.html', 
                long_summary: [{'title': 'FTT Exchange Token Recovers 35% Following Interview', 'url': 'https://finance.yahoo.com/news/ftx-token-jumps-after-ceo-says-viable-business-could-emerge-from-bankruptcy-172411742.html', 'text':[{key: 'Main company', value: 'FTX'}, {key: 'Business/service', value: 'Crypto exchange'}, {key: 'Valuation', value: '$70/token at peak'}, {key: 'Liquid assets', value: '$5.5B ($1.7B cash, $3.5B crypto assets, $0.3B securities)'}, {key: 'Non-strategic illiquid investments', value: '$4.6B'}, {key: 'Business decisions', value: [['Type', 'Details'], ['Hired Sullivan & Cromwell', '$20.5M'], ['Appointed independent examiner', 'U.S. Trustee']]}, {key: 'Personnel', value: [['Sam Bankman-Fried', 'Founder'], ['Gary Wang', 'Co-founder'], ['Caroline Ellison', 'Former CEO, Alameda Research'], ['John J. Ray III', 'FTX Group CEO']]}] }], qa_list: []}
            ]}
        ],
    DEFAULT_STLYE_LIST: [ 
        { id: 1, val: "travel", name: "Travel", disabled: false },
        //{ id: 2, val: "legal", name: "Legal" },
        { id: 3, val: "bizanalytics", name: "Biz. Analytics", disabled: false },
        { id: 5, val: "spaper", name: "Sci. Paper", disabled: false },
        //{ id: 22, val: "---", name: "---", disabled: false },
        { id: 4, val: "generic", name: "Generic", disabled: false },
        { id: 5, val: "bulletsgeneric", name: "Bullet Points", disabled: false },
        { id: 6, val: "explain", name: "Explain", disabled: false },
        { id: 7, val: "tabularize", name: "Generic Table", disabled: false },
        { id: 8, val: "custom", name: "Custom", disabled: true },],
    DEFAULT_TITLE_OUTPUT: "Welcome to Essence!",
    DEFAULT_TEXT_OUTPUT: [
        {'key': "Get started", 'value': "Go to Login and sign-up!"}, 
        {'key': "Quick value", 'value': "Surf to a website (or PDF), choose a style (Travel, Scientific, Business, etc.) and click the 'Process' button (Screen+Gear icon) to get a structured summary of the page."}, 
        {'key': "Usability example", 'value': "Click the Books icon to see performance examples."}, 
        {'key': "Warning", 'value': "This app relies heavily on large language models - which don't always get things right. Treat the app as a \"co-pilot\" rather than a flawless AI. Please use with caution."},
        {'key': "See About", 'value': "This is very much a work in progress and we'd love your feedback."}
    ],
    RANDOM_TIPS: [
        {'key': "Random tip", 'value': "You can enable processing of offline files by right clicking the extension icon, then clicking 'Manage Extensions' and then 'Allow access to file URLs'."},
        {'key': "Random tip", 'value': "The session title is automatically generated as you continue processing pages, but you can change it eventually, before saving or exporting it."},
        {'key': "Random tip", 'value': "In the settings page you can enable/disable the tip popups, output reset and Notion integration."},
        {'key': "Random tip", 'value': "This app relies heavily on large language models - which don't always get things right. Treat the app as a \"co-pilot\" rather than a flawless AI. Please use with caution."},
        {'key': "Random tip", 'value': "This is very much a work in progress and we'd love your feedback - see About page."},
        {'key': "Random tip", 'value': "You can right click on a page or marked text in it and use the app menu there without first opening the extension."},
        {'key': "Random tip", 'value': "You can enable/disable auto-opening of the extension on some domains by checking the box in the bottom of this page."},
        {'key': "Random tip", 'value': "Getting an answer sometimes takes a while, either because it takes the server a while to download the page (for example, for a long PDF) or because the text is quite long for the AI models. The easiest way to speed it up is to process chunks of the text, by marking it and using the Brush button."},
        {'key': "Random tip", 'value': "When editing an output header (the short bold text on the left here) and leaving it blank, both the header and its content will be deleted."},
        //{'key': "Random tip", 'value': "The questions-answers feature is powered by a search of relevant snippets in the text, followed by a coherent answer distillation. Since the search sometimes fails, the answer may miss information."}
    ],
    DEFAULT_WIDTH: 492, // px
    DEFAULT_WIDGET_WIDTH: 100, // px
    DEFAULT_WIDGET_HEIGHT: 100, // px
    MAX_TITLE_LENGTH: 100,
    MIN_TIME_SHOW_LOADING_ADVICE: 15000, // ms
    YOUTUBE_ID: "EGK6ic3eovg",
    DEFAULT_REMAINING_QUERIES: 50,
    DEFAULT_REMAINING_QUESTIONS: 50,
}